'use client'
import { useEffect, useState } from 'react'
import { ArrowRight, Bot, Check, LoaderCircle, Send, Sparkles } from 'lucide-react'
import { FeatureNav, SiteShell } from '@/components/site-shell'
import { companionReply, crowd, featureCopy, getFeature, replan } from '@/lib/travel-data'

export default function FeaturePage({ params }: { params: Promise<{ feature: string }> }) {
  const [slug, setSlug] = useState('companion')
  useEffect(() => { params.then((value) => setSlug(value.feature)) }, [params])
  const feature = getFeature(slug) ?? getFeature('companion')!
  const copy = featureCopy[feature.slug]
  return <SiteShell><section className="mx-auto max-w-7xl px-5 py-10 lg:px-10 lg:py-16"><div className="grid gap-10 lg:grid-cols-[.85fr_1.15fr]"><div><div className="flex size-14 items-center justify-center rounded-2xl bg-primary text-primary-foreground"><Bot className="size-7" /></div><p className="mt-7 font-mono text-xs font-bold uppercase tracking-[0.24em] text-primary">{feature.eyebrow}</p><h1 className="mt-3 max-w-2xl font-serif text-5xl font-semibold leading-[1.04] tracking-tight sm:text-6xl">{feature.title}</h1><p className="mt-5 max-w-xl text-base leading-7 text-muted-foreground">{feature.description}</p><div className="mt-8 flex flex-wrap gap-2"><span className="rounded-full bg-accent/50 px-3 py-2 text-xs font-bold">{copy.stat}</span><span className="rounded-full bg-secondary px-3 py-2 text-xs font-bold text-muted-foreground">Prototype backend connected</span></div></div><FeaturePanel slug={feature.slug} copy={copy} /></div><div className="mt-12 border-t border-border pt-8"><p className="font-mono text-xs font-bold uppercase tracking-[0.2em] text-primary">Keep exploring</p><h2 className="mt-2 font-serif text-3xl font-semibold">Build a more complete journey.</h2><div className="mt-5"><FeatureNav /></div></div>{feature.slug === 'crowd-planner' && <CrowdChart />}</section></SiteShell>
}

function FeaturePanel({ slug, copy }: { slug: string; copy: { action: string; stat: string; detail: string; options: string[] } }) {
  const [option, setOption] = useState(copy.options[0]); const [loading, setLoading] = useState(false); const [result, setResult] = useState(''); const [message, setMessage] = useState(''); const [chat, setChat] = useState<string[]>([])
  async function run() { setLoading(true); await new Promise((resolve) => setTimeout(resolve, 450)); if (slug === 'replanner') setResult(JSON.stringify(replan(option.includes('Rain') ? 'rain' : option.includes('closed') ? 'closed' : 'crowd'))); else if (slug === 'companion') setResult(companionReply(option)); else if (slug === 'crowd-planner') setResult('Your quiet window is 07:30–09:10. Expected crowd level: 22%.'); else if (slug === 'locals') setResult('Best match: Babu K. — 94% fit. Local benefit score: 92/100.'); else if (slug === 'sustainability') setResult('Electric shuttle + walking swap: −38% carbon, +₹120 local spend.'); else if (slug === 'culture') setResult('Malayalam: “Nanni” means thank you. Your effort matters more than perfect pronunciation.'); else setResult('3 nearby hidden matches found: a family kitchen, craft studio and quiet village trail.'); setLoading(false) }
  function send() { if (message.trim()) { setChat([...chat, `You: ${message}`, `Yatra: ${companionReply(message)}`]); setMessage('') } }
  return <div className="rounded-[2rem] border border-border bg-card p-5 shadow-xl sm:p-7"><p className="font-serif text-2xl font-semibold">Make it useful</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{copy.detail}</p>{slug === 'companion' ? <><div className="mt-7 flex min-h-64 flex-col gap-3 rounded-2xl bg-secondary/60 p-4">{chat.length === 0 && <p className="text-sm leading-6 text-muted-foreground">Ask about food, rain, etiquette, translations or timing.</p>}{chat.map((line, index) => <p key={index} className={`max-w-[90%] rounded-xl px-3 py-2 text-sm ${line.startsWith('You:') ? 'self-end bg-primary text-primary-foreground' : 'bg-card'}`}>{line}</p>)}</div><div className="mt-3 flex gap-2 rounded-2xl bg-secondary px-3 py-2"><input value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Ask Yatra something…" className="min-w-0 flex-1 bg-transparent px-2 text-sm outline-none" /><button onClick={send} aria-label="Send message" className="rounded-xl bg-primary p-2 text-primary-foreground"><Send className="size-4" /></button></div></> : <><div className="mt-7 flex flex-col gap-2">{copy.options.map((item) => <button key={item} onClick={() => setOption(item)} className={`flex items-center justify-between rounded-2xl border p-4 text-left text-sm font-semibold ${option === item ? 'border-primary bg-primary/5 text-primary' : 'border-border hover:bg-secondary'}`}>{item}{option === item && <Check className="size-4" />}</button>)}</div><button onClick={run} disabled={loading} className="mt-5 flex w-full items-center justify-center rounded-2xl bg-primary px-5 py-3.5 text-sm font-bold text-primary-foreground disabled:opacity-70">{loading ? <LoaderCircle className="mr-2 size-4 animate-spin" /> : <ArrowRight className="mr-2 size-4" />}{loading ? 'Thinking…' : copy.action}</button>{result && <ResultBox result={result} />}</>}</div>
}
function ResultBox({ result }: { result: string }) { let parsed: { title: string; stops: string[]; reason: string } | null = null; if (result.startsWith('{')) parsed = JSON.parse(result); return <div className="mt-5 rounded-2xl border border-primary/20 bg-accent/30 p-4 text-sm leading-6"><p className="mb-2 font-mono text-[10px] font-bold uppercase tracking-[0.2em] text-primary">Yatra recommendation</p>{parsed ? <><p className="font-serif text-xl font-semibold">{parsed.title}</p>{parsed.stops.map((stop) => <p key={stop} className="flex gap-2"><Check className="mt-1 size-4 text-primary" />{stop}</p>)}<p className="pt-2 text-muted-foreground">{parsed.reason}</p></> : <p>{result}</p>}</div> }
function CrowdChart() { return <div className="mt-8 grid grid-cols-6 gap-2 rounded-3xl border border-border bg-card p-5">{crowd.map((value, index) => <div key={index} className="flex flex-col items-center gap-2"><div className="flex h-28 w-full items-end rounded-xl bg-secondary"><div className="w-full rounded-xl bg-primary" style={{ height: `${value}%` }} /></div><span className="text-[10px] text-muted-foreground">{String(index + 6).padStart(2, '0')}:00</span></div>)}</div> }
