'use client'

import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { Menu, Navigation, Search, X } from 'lucide-react'
import { useState } from 'react'

const links = [{ href: '/', label: 'Overview' }, { href: '/explore', label: 'Explore' }, { href: '/trips', label: 'My trip' }, { href: '/locals', label: 'Meet locals' }, { href: '/companion', label: 'AI companion' }]

export function SiteShell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname(); const [open, setOpen] = useState(false)
  return <main className="min-h-screen bg-background text-foreground"><header className="sticky top-0 z-40 border-b border-border/80 bg-background/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-10"><Link href="/" className="flex items-center gap-3" onClick={() => setOpen(false)}><span className="flex size-10 items-center justify-center rounded-2xl bg-primary text-primary-foreground"><Navigation className="size-5" /></span><span><span className="block font-mono text-[10px] font-bold uppercase tracking-[0.24em] text-primary">Yatra / AI</span><span className="block font-serif text-lg font-semibold leading-none">Go beyond the map</span></span></Link><nav className="hidden items-center gap-1 rounded-full border border-border bg-card p-1 md:flex">{links.map((link) => <Link key={link.href} href={link.href} className={`rounded-full px-4 py-2 text-sm font-semibold ${pathname === link.href ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-secondary hover:text-foreground'}`}>{link.label}</Link>)}</nav><div className="flex items-center gap-2"><Link href="/explore" aria-label="Search travel" className="rounded-full p-2.5 text-muted-foreground hover:bg-secondary"><Search className="size-5" /></Link><button onClick={() => setOpen(!open)} aria-label="Open menu" className="rounded-full border border-border p-2 md:hidden">{open ? <X className="size-5" /> : <Menu className="size-5" />}</button></div></div>{open && <nav className="mx-5 mb-4 flex flex-col gap-1 rounded-2xl border border-border bg-card p-2 shadow-lg md:hidden">{links.map((link) => <Link key={link.href} href={link.href} onClick={() => setOpen(false)} className="rounded-xl p-3 text-sm font-semibold hover:bg-secondary">{link.label}</Link>)}</nav>}</header>{children}<footer className="border-t border-border"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-8 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between lg:px-10"><p><span className="font-semibold text-foreground">Yatra AI</span> · SIH tourism prototype</p><div className="flex flex-wrap gap-5"><Link href="/explore">Discover</Link><Link href="/sustainability">Impact</Link><Link href="/culture">Culture guide</Link><Link href="/locals">For local businesses</Link></div></div></footer></main>
}

export function PrimaryLink({ href, children }: { href: string; children: React.ReactNode }) { return <Link href={href} className="rounded-full bg-primary px-5 py-3 text-sm font-bold text-primary-foreground shadow-lg transition hover:-translate-y-0.5">{children}</Link> }
export function FeatureNav() { return <div className="flex flex-wrap gap-2">{['replanner','hidden-experiences','crowd-planner','companion','locals','sustainability','culture'].map((slug) => <Link key={slug} href={`/${slug}`} className="rounded-full border border-border bg-card px-3 py-2 text-xs font-semibold text-muted-foreground hover:border-primary hover:text-primary">{slug.replaceAll('-', ' ')}</Link>)}</div> }
